"""tabel percobaan masuk

Revision ID: 1a767843f909
Revises: 978d95799363
Create Date: 2026-08-11 17:13:11.700462

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a767843f909"
down_revision: str | Sequence[str] | None = "978d95799363"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "percobaan_masuk",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nama_pengguna", sa.String(length=50), nullable=False),
        sa.Column("alamat_ip", sa.String(length=45), nullable=False),
        sa.Column("berhasil", sa.Boolean(), nullable=False),
        sa.Column(
            "dibuat_pada",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "diubah_pada",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_percobaan_masuk_alamat_ip"), "percobaan_masuk", ["alamat_ip"], unique=False
    )
    op.create_index(
        op.f("ix_percobaan_masuk_diubah_pada"), "percobaan_masuk", ["diubah_pada"], unique=False
    )
    op.create_index(
        op.f("ix_percobaan_masuk_nama_pengguna"), "percobaan_masuk", ["nama_pengguna"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_percobaan_masuk_nama_pengguna"), table_name="percobaan_masuk")
    op.drop_index(op.f("ix_percobaan_masuk_diubah_pada"), table_name="percobaan_masuk")
    op.drop_index(op.f("ix_percobaan_masuk_alamat_ip"), table_name="percobaan_masuk")
    op.drop_table("percobaan_masuk")
    # ### end Alembic commands ###
