"""tabel mutasi stok

Revision ID: 6565472f029f
Revises: cc070bd7d875
Create Date: 2026-08-12 16:02:02.394841

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6565472f029f"
down_revision: str | Sequence[str] | None = "cc070bd7d875"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mutasi_stok",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("produk_id", sa.Integer(), nullable=False),
        sa.Column(
            "tipe",
            sa.Enum(
                "stok_awal",
                "penjualan",
                "retur_penjualan",
                "pembelian",
                "retur_pembelian",
                "penyesuaian",
                "opname",
                name="tipe_mutasi",
            ),
            nullable=False,
        ),
        sa.Column("jumlah", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("saldo_sesudah", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("hpp_saat_itu", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("rujukan_tipe", sa.String(length=30), nullable=True),
        sa.Column("rujukan_id", sa.Integer(), nullable=True),
        sa.Column("alasan", sa.Text(), nullable=True),
        sa.Column("pengguna_id", sa.Integer(), nullable=False),
        sa.Column(
            "dibuat_pada",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "diubah_pada",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pengguna_id"],
            ["pengguna.id"],
        ),
        sa.ForeignKeyConstraint(
            ["produk_id"],
            ["produk.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mutasi_stok_diubah_pada"), "mutasi_stok", ["diubah_pada"], unique=False
    )
    op.create_index(op.f("ix_mutasi_stok_produk_id"), "mutasi_stok", ["produk_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mutasi_stok_produk_id"), table_name="mutasi_stok")
    op.drop_index(op.f("ix_mutasi_stok_diubah_pada"), table_name="mutasi_stok")
    op.drop_table("mutasi_stok")
    # ### end Alembic commands ###
