"""tabel sesi kas dan penjualan

Revision ID: 679be73b1e4e
Revises: 6565472f029f
Create Date: 2026-08-12 16:55:07.227992

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "679be73b1e4e"
down_revision: str | Sequence[str] | None = "6565472f029f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sesi_kas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kasir_id", sa.Integer(), nullable=False),
        sa.Column("waktu_buka", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modal_awal", sa.BigInteger(), nullable=False),
        sa.Column("waktu_tutup", sa.DateTime(timezone=True), nullable=True),
        sa.Column("kas_sistem", sa.BigInteger(), nullable=True),
        sa.Column("kas_fisik", sa.BigInteger(), nullable=True),
        sa.Column("selisih", sa.BigInteger(), nullable=True),
        sa.Column("catatan", sa.Text(), nullable=True),
        sa.Column("status", sa.Enum("terbuka", "tertutup", name="status_sesi"), nullable=False),
        sa.Column(
            "dibuat_pada",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "diubah_pada",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["kasir_id"],
            ["pengguna.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sesi_kas_diubah_pada"), "sesi_kas", ["diubah_pada"], unique=False)
    op.create_index(op.f("ix_sesi_kas_kasir_id"), "sesi_kas", ["kasir_id"], unique=False)
    op.create_table(
        "penjualan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid_klien", sa.UUID(), nullable=False),
        sa.Column("nomor_nota", sa.String(length=30), nullable=False),
        sa.Column("sesi_kas_id", sa.Integer(), nullable=False),
        sa.Column("kasir_id", sa.Integer(), nullable=False),
        sa.Column("waktu_transaksi", sa.DateTime(timezone=True), nullable=False),
        sa.Column("waktu_diterima", sa.DateTime(timezone=True), nullable=False),
        sa.Column("subtotal", sa.BigInteger(), nullable=False),
        sa.Column("diskon_nota", sa.BigInteger(), nullable=False),
        sa.Column("pembulatan", sa.BigInteger(), nullable=False),
        sa.Column("total", sa.BigInteger(), nullable=False),
        sa.Column(
            "metode_bayar",
            sa.Enum("tunai", "transfer", "qris", name="metode_bayar"),
            nullable=False,
        ),
        sa.Column("dibayar", sa.BigInteger(), nullable=False),
        sa.Column("kembalian", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("selesai", "sebagian_diretur", "diretur_penuh", name="status_nota"),
            nullable=False,
        ),
        sa.Column("catatan", sa.Text(), nullable=True),
        sa.Column(
            "dibuat_pada",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "diubah_pada",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["kasir_id"],
            ["pengguna.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sesi_kas_id"],
            ["sesi_kas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nomor_nota"),
        sa.UniqueConstraint("uuid_klien"),
    )
    op.create_index(op.f("ix_penjualan_diubah_pada"), "penjualan", ["diubah_pada"], unique=False)
    op.create_index(op.f("ix_penjualan_kasir_id"), "penjualan", ["kasir_id"], unique=False)
    op.create_index(op.f("ix_penjualan_sesi_kas_id"), "penjualan", ["sesi_kas_id"], unique=False)
    op.create_index(
        op.f("ix_penjualan_waktu_transaksi"), "penjualan", ["waktu_transaksi"], unique=False
    )
    op.create_table(
        "item_penjualan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("penjualan_id", sa.Integer(), nullable=False),
        sa.Column("produk_id", sa.Integer(), nullable=False),
        sa.Column("satuan_id", sa.Integer(), nullable=False),
        sa.Column("nama_produk", sa.String(length=150), nullable=False),
        sa.Column("nama_satuan", sa.String(length=20), nullable=False),
        sa.Column("faktor", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("jumlah", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("jumlah_dasar", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("harga_satuan", sa.BigInteger(), nullable=False),
        sa.Column("diskon", sa.BigInteger(), nullable=False),
        sa.Column("subtotal", sa.BigInteger(), nullable=False),
        sa.Column("hpp_saat_itu", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column(
            "dibuat_pada",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "diubah_pada",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["penjualan_id"],
            ["penjualan.id"],
        ),
        sa.ForeignKeyConstraint(
            ["produk_id"],
            ["produk.id"],
        ),
        sa.ForeignKeyConstraint(
            ["satuan_id"],
            ["satuan_produk.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_item_penjualan_diubah_pada"), "item_penjualan", ["diubah_pada"], unique=False
    )
    op.create_index(
        op.f("ix_item_penjualan_penjualan_id"), "item_penjualan", ["penjualan_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_item_penjualan_penjualan_id"), table_name="item_penjualan")
    op.drop_index(op.f("ix_item_penjualan_diubah_pada"), table_name="item_penjualan")
    op.drop_table("item_penjualan")
    op.drop_index(op.f("ix_penjualan_waktu_transaksi"), table_name="penjualan")
    op.drop_index(op.f("ix_penjualan_sesi_kas_id"), table_name="penjualan")
    op.drop_index(op.f("ix_penjualan_kasir_id"), table_name="penjualan")
    op.drop_index(op.f("ix_penjualan_diubah_pada"), table_name="penjualan")
    op.drop_table("penjualan")
    op.drop_index(op.f("ix_sesi_kas_kasir_id"), table_name="sesi_kas")
    op.drop_index(op.f("ix_sesi_kas_diubah_pada"), table_name="sesi_kas")
    op.drop_table("sesi_kas")
    # ### end Alembic commands ###
