"""tabel pengguna

Revision ID: 759518f6537f
Revises:
Create Date: 2026-08-11 17:01:57.668295

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "759518f6537f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pengguna",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nama_pengguna", sa.String(length=50), nullable=False),
        sa.Column("nama_lengkap", sa.String(length=100), nullable=False),
        sa.Column("sandi_hash", sa.String(), nullable=False),
        sa.Column("peran", sa.Enum("pemilik", "kasir", name="peran"), nullable=False),
        sa.Column("aktif", sa.Boolean(), nullable=False),
        sa.Column(
            "dibuat_pada",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "diubah_pada",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nama_pengguna"),
    )
    op.create_index(op.f("ix_pengguna_diubah_pada"), "pengguna", ["diubah_pada"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pengguna_diubah_pada"), table_name="pengguna")
    op.drop_table("pengguna")
    # ### end Alembic commands ###
