"""tabel token segar

Revision ID: 978d95799363
Revises: 759518f6537f
Create Date: 2026-08-11 17:05:40.777394

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "978d95799363"
down_revision: str | Sequence[str] | None = "759518f6537f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_segar",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pengguna_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("kedaluwarsa_pada", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dicabut_pada", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "dibuat_pada",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "diubah_pada",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pengguna_id"],
            ["pengguna.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_token_segar_diubah_pada"), "token_segar", ["diubah_pada"], unique=False
    )
    op.create_index(
        op.f("ix_token_segar_pengguna_id"), "token_segar", ["pengguna_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_token_segar_pengguna_id"), table_name="token_segar")
    op.drop_index(op.f("ix_token_segar_diubah_pada"), table_name="token_segar")
    op.drop_table("token_segar")
    # ### end Alembic commands ###
