"""tabel kategori, produk, satuan

Revision ID: cc070bd7d875
Revises: 1a767843f909
Create Date: 2026-08-12 15:59:44.241254

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc070bd7d875"
down_revision: str | Sequence[str] | None = "1a767843f909"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kategori",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nama", sa.String(length=60), nullable=False),
        sa.Column(
            "dibuat_pada",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "diubah_pada",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nama"),
    )
    op.create_index(op.f("ix_kategori_diubah_pada"), "kategori", ["diubah_pada"], unique=False)
    op.create_table(
        "produk",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kode", sa.String(length=30), nullable=False),
        sa.Column("nama", sa.String(length=150), nullable=False),
        sa.Column("kategori_id", sa.Integer(), nullable=True),
        sa.Column("satuan_dasar", sa.String(length=20), nullable=False),
        sa.Column("stok", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("stok_minimum", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("hpp", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("perlu_dilengkapi", sa.Boolean(), nullable=False),
        sa.Column("uuid_klien", sa.UUID(), nullable=True),
        sa.Column("aktif", sa.Boolean(), nullable=False),
        sa.Column(
            "dibuat_pada",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "diubah_pada",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["kategori_id"],
            ["kategori.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kode"),
        sa.UniqueConstraint("uuid_klien"),
    )
    op.create_index(op.f("ix_produk_diubah_pada"), "produk", ["diubah_pada"], unique=False)
    op.create_index(op.f("ix_produk_nama"), "produk", ["nama"], unique=False)
    op.create_table(
        "satuan_produk",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("produk_id", sa.Integer(), nullable=False),
        sa.Column("nama", sa.String(length=20), nullable=False),
        sa.Column("faktor", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("harga_jual", sa.BigInteger(), nullable=False),
        sa.Column("barcode", sa.String(length=32), nullable=True),
        sa.Column("is_dasar", sa.Boolean(), nullable=False),
        sa.Column("aktif", sa.Boolean(), nullable=False),
        sa.Column(
            "dibuat_pada",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "diubah_pada",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("faktor > 0", name="ck_satuan_faktor_positif"),
        sa.CheckConstraint("harga_jual >= 0", name="ck_satuan_harga_tak_negatif"),
        sa.ForeignKeyConstraint(
            ["produk_id"],
            ["produk.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("barcode"),
        sa.UniqueConstraint("produk_id", "nama", name="uq_satuan_produk_nama"),
    )
    op.create_index(
        op.f("ix_satuan_produk_diubah_pada"), "satuan_produk", ["diubah_pada"], unique=False
    )
    op.create_index(
        op.f("ix_satuan_produk_produk_id"), "satuan_produk", ["produk_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_satuan_produk_produk_id"), table_name="satuan_produk")
    op.drop_index(op.f("ix_satuan_produk_diubah_pada"), table_name="satuan_produk")
    op.drop_table("satuan_produk")
    op.drop_index(op.f("ix_produk_nama"), table_name="produk")
    op.drop_index(op.f("ix_produk_diubah_pada"), table_name="produk")
    op.drop_table("produk")
    op.drop_index(op.f("ix_kategori_diubah_pada"), table_name="kategori")
    op.drop_table("kategori")
    # ### end Alembic commands ###
