/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Akar Penjelas
         * @description Menjelaskan diri saat alamat ini dibuka di browser.
         *
         *     Alamat ini melayani API, bukan halaman. Tanpa jawaban ini, membukanya
         *     di browser hanya memberi 404 kosong yang tidak memberi tahu apa pun,
         *     padahal itu hal pertama yang dilakukan orang saat mencoba sistemnya.
         */
        get: operations["akar_penjelas__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sehat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sehat
         * @description Menyentuh basis data, bukan sekadar menjawab.
         *
         *     Endpoint kesehatan yang tidak menyentuh basis data akan menjawab
         *     "sehat" meski basis datanya mati, dan itu lebih berbahaya daripada
         *     tidak punya endpoint kesehatan sama sekali.
         */
        get: operations["sehat_api_v1_sehat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/masuk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Masuk */
        post: operations["masuk_api_v1_auth_masuk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/segarkan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Segarkan */
        post: operations["segarkan_api_v1_auth_segarkan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/keluar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Keluar */
        post: operations["keluar_api_v1_auth_keluar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/saya": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Saya */
        get: operations["saya_api_v1_auth_saya_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/ubah-sandi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ubah Sandi */
        post: operations["ubah_sandi_api_v1_auth_ubah_sandi_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pengguna": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar */
        get: operations["daftar_api_v1_pengguna_get"];
        put?: never;
        /** Buat */
        post: operations["buat_api_v1_pengguna_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pengguna/{pengguna_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Ubah */
        patch: operations["ubah_api_v1_pengguna__pengguna_id__patch"];
        trace?: never;
    };
    "/api/v1/pengguna/{pengguna_id}/atur-ulang-sandi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atur Ulang */
        post: operations["atur_ulang_api_v1_pengguna__pengguna_id__atur_ulang_sandi_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/produk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar Produk */
        get: operations["daftar_produk_api_v1_produk_get"];
        put?: never;
        /** Buat Produk */
        post: operations["buat_produk_api_v1_produk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/produk/{produk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Satu Produk */
        get: operations["satu_produk_api_v1_produk__produk_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Ubah Produk */
        patch: operations["ubah_produk_api_v1_produk__produk_id__patch"];
        trace?: never;
    };
    "/api/v1/produk/kilat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Produk Kilat */
        post: operations["produk_kilat_api_v1_produk_kilat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/produk/{produk_id}/satuan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tambah Satuan */
        post: operations["tambah_satuan_api_v1_produk__produk_id__satuan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/produk/{produk_id}/kartu-stok": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kartu Stok */
        get: operations["kartu_stok_api_v1_produk__produk_id__kartu_stok_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kategori": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar Kategori */
        get: operations["daftar_kategori_api_v1_kategori_get"];
        put?: never;
        /** Buat Kategori */
        post: operations["buat_kategori_api_v1_kategori_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/penyesuaian-stok": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Penyesuaian Stok */
        post: operations["penyesuaian_stok_api_v1_penyesuaian_stok_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stok/menipis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stok Menipis */
        get: operations["stok_menipis_api_v1_stok_menipis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stok/minus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stok Minus */
        get: operations["stok_minus_api_v1_stok_minus_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/produk/impor/contoh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Contoh Impor
         * @description Berkas contoh berisi kepala kolom yang benar.
         */
        get: operations["contoh_impor_api_v1_produk_impor_contoh_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/produk/impor/pratinjau": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pratinjau Impor */
        post: operations["pratinjau_impor_api_v1_produk_impor_pratinjau_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/produk/impor/jalankan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Jalankan Impor */
        post: operations["jalankan_impor_api_v1_produk_impor_jalankan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sesi-kas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Buka Sesi */
        post: operations["buka_sesi_api_v1_sesi_kas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sesi-kas/aktif": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sesi Aktif */
        get: operations["sesi_aktif_api_v1_sesi_kas_aktif_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sesi-kas/{kas_id}/kas-sistem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kas Sistem
         * @description Kas yang seharusnya ada di laci, untuk dibandingkan saat menutup.
         */
        get: operations["kas_sistem_api_v1_sesi_kas__kas_id__kas_sistem_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sesi-kas/{kas_id}/tutup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tutup Sesi */
        post: operations["tutup_sesi_api_v1_sesi_kas__kas_id__tutup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/penjualan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar Penjualan */
        get: operations["daftar_penjualan_api_v1_penjualan_get"];
        put?: never;
        /**
         * Catat Penjualan
         * @description 201 bila baru disimpan, 200 bila UUID-nya sudah pernah masuk.
         *
         *     Perbedaan kode itu penting bagi perangkat: 200 berarti pengiriman
         *     ulang berhasil dikenali, bukan bahwa notanya tercatat dua kali.
         */
        post: operations["catat_penjualan_api_v1_penjualan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AturUlangSandi */
        AturUlangSandi: {
            /** Sandi Baru */
            sandi_baru: string;
        };
        /** BarisGagal */
        BarisGagal: {
            /** Baris */
            baris: number;
            /** Alasan */
            alasan: string;
        };
        /** Body_jalankan_impor_api_v1_produk_impor_jalankan_post */
        Body_jalankan_impor_api_v1_produk_impor_jalankan_post: {
            /** Berkas */
            berkas: string;
        };
        /** Body_pratinjau_impor_api_v1_produk_impor_pratinjau_post */
        Body_pratinjau_impor_api_v1_produk_impor_pratinjau_post: {
            /** Berkas */
            berkas: string;
        };
        /** BuatPengguna */
        BuatPengguna: {
            /** Nama Pengguna */
            nama_pengguna: string;
            /** Nama Lengkap */
            nama_lengkap: string;
            /** Sandi */
            sandi: string;
            peran: components["schemas"]["Peran"];
        };
        /** BukaSesi */
        BukaSesi: {
            /** Modal Awal */
            modal_awal: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HasilImpor
         * @description Hasil pratinjau maupun penjalanan impor.
         *
         *     Kegagalan dilaporkan per baris dengan nomor barisnya, bukan sebagai
         *     satu pesan "impor gagal". Pemilik yang mengimpor ratusan produk perlu
         *     tahu baris mana yang harus dibetulkan, bukan sekadar bahwa ada yang
         *     salah (STK-04).
         */
        HasilImpor: {
            /** Sah */
            sah: number;
            /** Gagal */
            gagal: components["schemas"]["BarisGagal"][];
            /**
             * Tersimpan
             * @default 0
             */
            tersimpan: number;
        };
        /** ItemKeluar */
        ItemKeluar: {
            /** Id */
            id: number;
            /** Produk Id */
            produk_id: number;
            /** Nama Produk */
            nama_produk: string;
            /** Nama Satuan */
            nama_satuan: string;
            /** Jumlah */
            jumlah: string;
            /** Jumlah Dasar */
            jumlah_dasar: string;
            /** Harga Satuan */
            harga_satuan: number;
            /** Diskon */
            diskon: number;
            /** Subtotal */
            subtotal: number;
            /** Hpp Saat Itu */
            hpp_saat_itu: string;
        };
        /**
         * ItemMasuk
         * @description Satu baris nota yang dikirim perangkat.
         *
         *     Merujuk produk lewat `produk_id` + `satuan_id` (produk yang sudah
         *     dikenal) ATAU lewat `produk_baru` (hasil tambah cepat, termasuk yang
         *     dibuat saat offline). Tidak pernah keduanya (bab 05 §5.5).
         */
        ItemMasuk: {
            /** Produk Id */
            produk_id?: number | null;
            /** Satuan Id */
            satuan_id?: number | null;
            produk_baru?: components["schemas"]["ProdukKilat"] | null;
            /** Jumlah */
            jumlah: number | string;
            /** Harga Satuan */
            harga_satuan: number;
            /**
             * Diskon
             * @default 0
             */
            diskon: number;
            /** Subtotal */
            subtotal: number;
        };
        /** JawabanToken */
        JawabanToken: {
            /** Token Akses */
            token_akses: string;
            /** Token Segar */
            token_segar: string;
        };
        /** KategoriKeluar */
        KategoriKeluar: {
            /** Id */
            id: number;
            /** Nama */
            nama: string;
        };
        /** KategoriMasuk */
        KategoriMasuk: {
            /** Nama */
            nama: string;
        };
        /**
         * MetodeBayar
         * @enum {string}
         */
        MetodeBayar: "tunai" | "transfer" | "qris";
        /** MutasiKeluar */
        MutasiKeluar: {
            /** Id */
            id: number;
            /** Tipe */
            tipe: string;
            /** Jumlah */
            jumlah: string;
            /** Saldo Sesudah */
            saldo_sesudah: string;
            /** Hpp Saat Itu */
            hpp_saat_itu: string;
            /** Rujukan Tipe */
            rujukan_tipe: string | null;
            /** Rujukan Id */
            rujukan_id: number | null;
            /** Alasan */
            alasan: string | null;
            /** Pengguna Id */
            pengguna_id: number;
        };
        /**
         * PenggunaKeluar
         * @description Bentuk pengguna yang dikirim keluar.
         *
         *     sandi_hash sengaja tidak ada di sini. Bentuk keluaran yang menyebut
         *     kolomnya satu per satu lebih aman daripada yang membuang beberapa,
         *     karena kolom sensitif yang ditambahkan kelak tidak ikut bocor.
         */
        PenggunaKeluar: {
            /** Id */
            id: number;
            /** Nama Pengguna */
            nama_pengguna: string;
            /** Nama Lengkap */
            nama_lengkap: string;
            peran: components["schemas"]["Peran"];
            /** Aktif */
            aktif: boolean;
        };
        /** PenjualanKeluar */
        PenjualanKeluar: {
            /** Id */
            id: number;
            /**
             * Uuid Klien
             * Format: uuid
             */
            uuid_klien: string;
            /** Nomor Nota */
            nomor_nota: string;
            /** Sesi Kas Id */
            sesi_kas_id: number;
            /** Kasir Id */
            kasir_id: number;
            /**
             * Waktu Transaksi
             * Format: date-time
             */
            waktu_transaksi: string;
            /** Subtotal */
            subtotal: number;
            /** Diskon Nota */
            diskon_nota: number;
            /** Pembulatan */
            pembulatan: number;
            /** Total */
            total: number;
            metode_bayar: components["schemas"]["MetodeBayar"];
            /** Dibayar */
            dibayar: number;
            /** Kembalian */
            kembalian: number;
            /** Status */
            status: string;
            /** Item */
            item: components["schemas"]["ItemKeluar"][];
        };
        /** PenjualanMasuk */
        PenjualanMasuk: {
            /**
             * Uuid Klien
             * Format: uuid
             */
            uuid_klien: string;
            /** Nomor Nota */
            nomor_nota: string;
            /**
             * Waktu Transaksi
             * Format: date-time
             */
            waktu_transaksi: string;
            /** @default tunai */
            metode_bayar: components["schemas"]["MetodeBayar"];
            /**
             * Diskon Nota
             * @default 0
             */
            diskon_nota: number;
            /**
             * Pembulatan
             * @default 0
             */
            pembulatan: number;
            /** Total */
            total: number;
            /** Dibayar */
            dibayar: number;
            /** Kembalian */
            kembalian: number;
            /** Catatan */
            catatan?: string | null;
            /** Item */
            item: components["schemas"]["ItemMasuk"][];
        };
        /** PenyesuaianStok */
        PenyesuaianStok: {
            /** Produk Id */
            produk_id: number;
            /** Jumlah */
            jumlah: number | string;
            /** Alasan */
            alasan: string;
        };
        /**
         * Peran
         * @enum {string}
         */
        Peran: "pemilik" | "kasir";
        /** PermintaanMasuk */
        PermintaanMasuk: {
            /** Nama Pengguna */
            nama_pengguna: string;
            /** Sandi */
            sandi: string;
        };
        /** PermintaanSegarkan */
        PermintaanSegarkan: {
            /** Token Segar */
            token_segar: string;
        };
        /**
         * ProdukKeluar
         * @description Bentuk lengkap, untuk peran pemilik.
         */
        ProdukKeluar: {
            /** Id */
            id: number;
            /** Kode */
            kode: string;
            /** Nama */
            nama: string;
            /** Kategori Id */
            kategori_id: number | null;
            /** Satuan Dasar */
            satuan_dasar: string;
            /** Stok */
            stok: string;
            /** Stok Minimum */
            stok_minimum: string;
            /** Hpp */
            hpp: string;
            /** Perlu Dilengkapi */
            perlu_dilengkapi: boolean;
            /** Aktif */
            aktif: boolean;
            /** Satuan */
            satuan: components["schemas"]["SatuanKeluar"][];
        };
        /**
         * ProdukKeluarKasir
         * @description Bentuk untuk peran kasir: TANPA hpp.
         *
         *     Kolomnya disebut satu per satu, bukan mewarisi lalu membuang, supaya
         *     kolom sensitif yang ditambahkan kelak tidak ikut bocor karena lupa
         *     dibuang (bab 08 §8.1).
         */
        ProdukKeluarKasir: {
            /** Id */
            id: number;
            /** Kode */
            kode: string;
            /** Nama */
            nama: string;
            /** Kategori Id */
            kategori_id: number | null;
            /** Satuan Dasar */
            satuan_dasar: string;
            /** Stok */
            stok: string;
            /** Stok Minimum */
            stok_minimum: string;
            /** Perlu Dilengkapi */
            perlu_dilengkapi: boolean;
            /** Aktif */
            aktif: boolean;
            /** Satuan */
            satuan: components["schemas"]["SatuanKeluar"][];
        };
        /**
         * ProdukKilat
         * @description Tambah cepat saat transaksi: nama dan harga saja (STK-05).
         */
        ProdukKilat: {
            /** Nama */
            nama: string;
            /** Harga */
            harga: number;
            /** Uuid Klien */
            uuid_klien?: string | null;
        };
        /** ProdukMasuk */
        ProdukMasuk: {
            /** Kode */
            kode: string;
            /** Nama */
            nama: string;
            /** Kategori Id */
            kategori_id?: number | null;
            /** Satuan Dasar */
            satuan_dasar: string;
            /**
             * Stok Minimum
             * @default 0
             */
            stok_minimum: number | string;
            /**
             * Stok Awal
             * @default 0
             */
            stok_awal: number | string;
            /** Satuan */
            satuan: components["schemas"]["SatuanMasuk"][];
        };
        /** ProdukUbah */
        ProdukUbah: {
            /** Nama */
            nama?: string | null;
            /** Kategori Id */
            kategori_id?: number | null;
            /** Stok Minimum */
            stok_minimum?: number | string | null;
            /** Perlu Dilengkapi */
            perlu_dilengkapi?: boolean | null;
            /** Aktif */
            aktif?: boolean | null;
        };
        /** SatuanKeluar */
        SatuanKeluar: {
            /** Id */
            id: number;
            /** Nama */
            nama: string;
            /** Faktor */
            faktor: string;
            /** Harga Jual */
            harga_jual: number;
            /** Barcode */
            barcode: string | null;
            /** Is Dasar */
            is_dasar: boolean;
            /** Aktif */
            aktif: boolean;
        };
        /** SatuanMasuk */
        SatuanMasuk: {
            /** Nama */
            nama: string;
            /** Faktor */
            faktor: number | string;
            /** Harga Jual */
            harga_jual: number;
            /** Barcode */
            barcode?: string | null;
            /**
             * Is Dasar
             * @default false
             */
            is_dasar: boolean;
        };
        /** SesiKasKeluar */
        SesiKasKeluar: {
            /** Id */
            id: number;
            /** Kasir Id */
            kasir_id: number;
            /**
             * Waktu Buka
             * Format: date-time
             */
            waktu_buka: string;
            /** Modal Awal */
            modal_awal: number;
            /** Waktu Tutup */
            waktu_tutup: string | null;
            /** Kas Sistem */
            kas_sistem: number | null;
            /** Kas Fisik */
            kas_fisik: number | null;
            /** Selisih */
            selisih: number | null;
            /** Catatan */
            catatan: string | null;
            /** Status */
            status: string;
        };
        /** TutupSesi */
        TutupSesi: {
            /** Kas Fisik */
            kas_fisik: number;
            /** Catatan */
            catatan?: string | null;
        };
        /** UbahPengguna */
        UbahPengguna: {
            /** Nama Lengkap */
            nama_lengkap?: string | null;
            peran?: components["schemas"]["Peran"] | null;
            /** Aktif */
            aktif?: boolean | null;
        };
        /** UbahSandiSendiri */
        UbahSandiSendiri: {
            /** Sandi Lama */
            sandi_lama: string;
            /** Sandi Baru */
            sandi_baru: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    akar_penjelas__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    sehat_api_v1_sehat_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    masuk_api_v1_auth_masuk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermintaanMasuk"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JawabanToken"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    segarkan_api_v1_auth_segarkan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermintaanSegarkan"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JawabanToken"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    keluar_api_v1_auth_keluar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermintaanSegarkan"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    saya_api_v1_auth_saya_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PenggunaKeluar"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ubah_sandi_api_v1_auth_ubah_sandi_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UbahSandiSendiri"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daftar_api_v1_pengguna_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PenggunaKeluar"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buat_api_v1_pengguna_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuatPengguna"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PenggunaKeluar"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ubah_api_v1_pengguna__pengguna_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                pengguna_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UbahPengguna"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PenggunaKeluar"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    atur_ulang_api_v1_pengguna__pengguna_id__atur_ulang_sandi_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                pengguna_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AturUlangSandi"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daftar_produk_api_v1_produk_get: {
        parameters: {
            query?: {
                cari?: string;
                kategori_id?: number | null;
                aktif?: boolean | null;
                perlu_dilengkapi?: boolean | null;
                batas?: number;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["ProdukKeluar"] | components["schemas"]["ProdukKeluarKasir"])[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buat_produk_api_v1_produk_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProdukMasuk"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProdukKeluar"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    satu_produk_api_v1_produk__produk_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                produk_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProdukKeluar"] | components["schemas"]["ProdukKeluarKasir"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ubah_produk_api_v1_produk__produk_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                produk_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProdukUbah"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProdukKeluar"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    produk_kilat_api_v1_produk_kilat_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProdukKilat"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProdukKeluar"] | components["schemas"]["ProdukKeluarKasir"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tambah_satuan_api_v1_produk__produk_id__satuan_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                produk_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SatuanMasuk"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SatuanKeluar"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kartu_stok_api_v1_produk__produk_id__kartu_stok_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                produk_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutasiKeluar"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daftar_kategori_api_v1_kategori_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KategoriKeluar"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buat_kategori_api_v1_kategori_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KategoriMasuk"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KategoriKeluar"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    penyesuaian_stok_api_v1_penyesuaian_stok_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PenyesuaianStok"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProdukKeluar"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stok_menipis_api_v1_stok_menipis_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["ProdukKeluar"] | components["schemas"]["ProdukKeluarKasir"])[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stok_minus_api_v1_stok_minus_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["ProdukKeluar"] | components["schemas"]["ProdukKeluarKasir"])[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    contoh_impor_api_v1_produk_impor_contoh_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pratinjau_impor_api_v1_produk_impor_pratinjau_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_pratinjau_impor_api_v1_produk_impor_pratinjau_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HasilImpor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jalankan_impor_api_v1_produk_impor_jalankan_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_jalankan_impor_api_v1_produk_impor_jalankan_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HasilImpor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buka_sesi_api_v1_sesi_kas_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BukaSesi"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesiKasKeluar"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sesi_aktif_api_v1_sesi_kas_aktif_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesiKasKeluar"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kas_sistem_api_v1_sesi_kas__kas_id__kas_sistem_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                kas_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tutup_sesi_api_v1_sesi_kas__kas_id__tutup_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                kas_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TutupSesi"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesiKasKeluar"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daftar_penjualan_api_v1_penjualan_get: {
        parameters: {
            query?: {
                dari?: string | null;
                sampai?: string | null;
                batas?: number;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PenjualanKeluar"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catat_penjualan_api_v1_penjualan_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PenjualanMasuk"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PenjualanKeluar"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
