// BERKAS INI DIBANGKITKAN OTOMATIS DARI OpenAPI. JANGAN DISUNTING TANGAN.
// Bangkitkan ulang dengan: npm run tipe
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/sehat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sehat
         * @description Menyentuh basis data, bukan sekadar menjawab.
         *
         *     Endpoint kesehatan yang tidak menyentuh basis data akan menjawab
         *     "sehat" meski basis datanya mati, dan itu lebih berbahaya daripada
         *     tidak punya endpoint kesehatan sama sekali.
         */
        get: operations["sehat_api_v1_sehat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/masuk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Masuk */
        post: operations["masuk_api_v1_auth_masuk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/segarkan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Segarkan */
        post: operations["segarkan_api_v1_auth_segarkan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/keluar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Keluar */
        post: operations["keluar_api_v1_auth_keluar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/saya": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Saya */
        get: operations["saya_api_v1_auth_saya_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/ubah-sandi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ubah Sandi */
        post: operations["ubah_sandi_api_v1_auth_ubah_sandi_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pengguna": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar */
        get: operations["daftar_api_v1_pengguna_get"];
        put?: never;
        /** Buat */
        post: operations["buat_api_v1_pengguna_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pengguna/{pengguna_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Ubah */
        patch: operations["ubah_api_v1_pengguna__pengguna_id__patch"];
        trace?: never;
    };
    "/api/v1/pengguna/{pengguna_id}/atur-ulang-sandi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atur Ulang */
        post: operations["atur_ulang_api_v1_pengguna__pengguna_id__atur_ulang_sandi_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AturUlangSandi */
        AturUlangSandi: {
            /** Sandi Baru */
            sandi_baru: string;
        };
        /** BuatPengguna */
        BuatPengguna: {
            /** Nama Pengguna */
            nama_pengguna: string;
            /** Nama Lengkap */
            nama_lengkap: string;
            /** Sandi */
            sandi: string;
            peran: components["schemas"]["Peran"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JawabanToken */
        JawabanToken: {
            /** Token Akses */
            token_akses: string;
            /** Token Segar */
            token_segar: string;
        };
        /**
         * PenggunaKeluar
         * @description Bentuk pengguna yang dikirim keluar.
         *
         *     sandi_hash sengaja tidak ada di sini. Bentuk keluaran yang menyebut
         *     kolomnya satu per satu lebih aman daripada yang membuang beberapa,
         *     karena kolom sensitif yang ditambahkan kelak tidak ikut bocor.
         */
        PenggunaKeluar: {
            /** Id */
            id: number;
            /** Nama Pengguna */
            nama_pengguna: string;
            /** Nama Lengkap */
            nama_lengkap: string;
            peran: components["schemas"]["Peran"];
            /** Aktif */
            aktif: boolean;
        };
        /**
         * Peran
         * @enum {string}
         */
        Peran: "pemilik" | "kasir";
        /** PermintaanMasuk */
        PermintaanMasuk: {
            /** Nama Pengguna */
            nama_pengguna: string;
            /** Sandi */
            sandi: string;
        };
        /** PermintaanSegarkan */
        PermintaanSegarkan: {
            /** Token Segar */
            token_segar: string;
        };
        /** UbahPengguna */
        UbahPengguna: {
            /** Nama Lengkap */
            nama_lengkap?: string | null;
            peran?: components["schemas"]["Peran"] | null;
            /** Aktif */
            aktif?: boolean | null;
        };
        /** UbahSandiSendiri */
        UbahSandiSendiri: {
            /** Sandi Lama */
            sandi_lama: string;
            /** Sandi Baru */
            sandi_baru: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sehat_api_v1_sehat_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    masuk_api_v1_auth_masuk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermintaanMasuk"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JawabanToken"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    segarkan_api_v1_auth_segarkan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermintaanSegarkan"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JawabanToken"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    keluar_api_v1_auth_keluar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermintaanSegarkan"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    saya_api_v1_auth_saya_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PenggunaKeluar"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ubah_sandi_api_v1_auth_ubah_sandi_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UbahSandiSendiri"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daftar_api_v1_pengguna_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PenggunaKeluar"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buat_api_v1_pengguna_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuatPengguna"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PenggunaKeluar"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ubah_api_v1_pengguna__pengguna_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                pengguna_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UbahPengguna"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PenggunaKeluar"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    atur_ulang_api_v1_pengguna__pengguna_id__atur_ulang_sandi_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                pengguna_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AturUlangSandi"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
